// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const ACTIVE_TENANT_KEY = "active_tenant_id";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Wrapper to automatically add X-Tenant header
const supabaseWithTenant = new Proxy(client, {
  get(target, prop) {
    const original = target[prop as keyof typeof target];
    
    // Intercept 'from' calls to add X-Tenant header
    if (prop === 'from') {
      return (table: string) => {
        const activeTenantId = localStorage.getItem(ACTIVE_TENANT_KEY);
        const builder = (original as any).call(target, table);
        
        if (activeTenantId) {
          return builder.headers({ 'X-Tenant': activeTenantId });
        }
        return builder;
      };
    }
    
    // Intercept 'rpc' calls to add X-Tenant header
    if (prop === 'rpc') {
      return (fn: string, params?: any) => {
        const activeTenantId = localStorage.getItem(ACTIVE_TENANT_KEY);
        const builder = (original as any).call(target, fn, params);
        
        if (activeTenantId) {
          return builder.headers({ 'X-Tenant': activeTenantId });
        }
        return builder;
      };
    }
    
    return original;
  }
});

export const supabase = supabaseWithTenant as typeof client;